project_create:
    pattern:  /create
    defaults: { _controller: ProjectBundle:Default:create }

project_view:
    pattern:  /view/{id}
    defaults: { _controller: ProjectBundle:Default:view }
    requirements: 
        id: \d+

project_list:
    pattern:  /list
    defaults: { _controller: ProjectBundle:Default:list }
