project_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ProjectBundle:Default:index }

project_create:
    pattern:  /create
    defaults: { _controller: ProjectBundle:Default:create }
