parameters:
#    project.example.class: Unicaen\Uniweb\ProjectBundle\Example

services:
#    project.example:
#        class: %project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
