admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

uniweb_user:
    resource: "@UniwebUserBundle/Resources/config/routing.yml"
    prefix:   /user

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /project

